### PR TITLE
Made time readable (account created at and updated at) in GithubUserInfoCommand

### PR DESCRIPTION
**Pull request by FC5570**
Made time readable (account created at and updated at) in GithubUserInfoCommand using moment

### CODE REVIEW

**Comment by Milo123459** [comment]
You updated the gitignore for no reason, ran npm which this project uses yarn and installed moment, please use dayjs instead

**Comment by FC5570** [comment]
fine

**Comment by FC5570** [comment]
ill do it in a bit

**Comment by FC5570** [comment]
wait i forgot to do something
aaa

**Pull request merged**
